version: '3.3'
services:
  db:
      image: postgres:13.0-alpine
      ports:
        - "5432:5432"
      volumes:
        - data_value:/var/lib/postgresql/data/
      env_file:
         - ./.env
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    env_file:
       - ./.env
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elastic_data:/var/lib/elasticsearch/data
  redis:
    container_name: redis
    image: redis:6-alpine
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
  web:
    build: ../django_api/
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    entrypoint: [ "sh", "/app/entrypoint.sh" ]
    depends_on:
      - db
    env_file:
       - ./.env
  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/openapi.yaml
volumes:
  static_value:
  media_value:
  data_value:
  redis_data:
  elastic_data: